export const CLIENTS = {
  TABLE_ID: 'tblRDICf8jQOOvQPf',
  CLIENT_ID: 'fldukexc33DyUohtd',
  CLIENT_NAME: 'fldPOYo9wPYMz8y5J',
  PHONE: 'fld2wGFrsIkZ2WJKX',
  EMAIL: 'fldAhLNSsczIN9W20',
  PROJECTS: 'fldg6O6PUTESQDTNn',
} as const

export const TASK_TEMPLATES = {
  TABLE_ID: 'tblfJFDNd2dcY1rUk',
  TASK_NAME: 'fldhUOs66e7p0IRhR',
  DEPARTMENT: 'fldpMqqDluxlVU7Qz',
  TEMPLATE_ORDER: 'fldQVmI7bzlIIllZQ',
  PROJECT_STAGE: 'fld7qqK3fUM8gjt6Z',
  PATH_CONDITION: 'fldBEIquy9HDAprY7',
  PHASE: 'flddIfmNdbQ45fVUd',
  REQUIRES_MANAGER_REVIEW: 'fldypvKqW3vyNsrY4',
  INSTRUCTIONS: 'fldsfoFM1RtZyT5wX',
  ARABIC_INSTRUCTIONS: 'fldT16R9UBY0UybHk',
} as const

export const TASKS = {
  TABLE_ID: 'tblOGEvAGcieHMPeX',
  TASK_NAME: 'fld6CUY7CqGjKS4v6',
  STATUS: 'fldZxo3damMz00LZI',
  DEPARTMENT: 'fldtXZWhiFvsQZdvd',
  ASSIGNED_TO: 'fld1vhOD1EY4n5cMb',
  TASK_ORDER: 'flddrIO6W7xqw6h8d',
  PROJECT: 'fldcHdzmQopPk4iEf',
  PROJECT_ITEM: 'fldzE0IPmOCVnKVmC',
  PROJECT_ID: 'fldBRW5E8ufAGPyJS',
  TASK_DOCUMENTS: 'fldWN2jRTtvVk10g7',
  HANDOVER_DOCUMENT: 'fldcLem7Z7fofiDoy',
  FILLERS_MISSING_ITEMS_LIST: 'fldSTM132XO86l19p',
  INSTRUCTIONS: 'fldQUxsUzEi1XQojd',
  ARABIC_INSTRUCTIONS: 'fldHVVySDTIqcJnob',
  MANAGER_REVIEW_STATUS: 'fldii3Ebi2lhAamuq',
  MANAGER_COMMENT: 'fldgHFTWfCZtJ1xOW',
  REQUIRES_MANAGER_REVIEW: 'fldEt5qAV8SiJoLvl',
  REQUIRES_MANAGER_REVIEW_MANUALLY: 'fldWCJd2f532pr2q6',
  POST_VISIT_OUTCOME: 'fld8tGPaBKroWulye',
  TASK_START_DATE: 'fldt8MlMioYdrNxik',
  COMPLETION_DATE: 'fldh1O00T2wn9ZNa7',
  STARTED_AT: 'fldegpR3li3Vmmk65',
  COMPLETED_AT: 'fldYARi0NN35mkTn6',
  ESTIMATED_DURATION: 'fldjXHjHDrSop0CAS',
  TEAM_DAYS_REQUIRED: 'fldYEkTSrzjrv3JfF',
  NO_OF_LABORS_PER_DAY: 'fldjxiY3vT2DwEUGc',
  INSTALLATION_DAYS: 'fldWfY6xisE0uhVHB',
  PLANNED_PROD_START_DATE: 'fldckX33LZhtyyJa6',
  EXPECTED_FAB_END_DATE: 'fldnPsZJ8hJCEx0qM',
  FABRICATION_PATH: 'fldAP4I4vbBGKjhyS',
  POST_CARPENTRY_PATH: 'fldZjKDnrPSJKLv09',
  PRODUCTION_START_PATH: 'fldGcM8dsJGvsWQF5',
  CONCEPT_DESIGN_APPROVAL: 'fldUcR8eVpooRHRWU',
  SAMPLE_APPROVAL: 'fldC6Pl923IfHdrk2',
  QUOTATION_OUTCOME: 'fldhYsEHetrQxTZ8k',
  QC_CHECK_AT_SITE_DONE: 'fldHrNVNe3abI0FBx',
  FILLERS_DONE: 'fldeITdFvnLVegVIy',
  PROJECT_STAGE: 'fldcS4LsNaEbpYEze',
  CLIENT: 'fldyYUTgOc7TNxl14',
  TASK_CREATED: 'fldHsDqsdVz90uAWc',
  TEMPLATE_ORDER: 'fldXxw74bcJFueDDX',
  PRIORITY_FLAG: 'fld5rZ88NiEmAeB4f',
  PROJECT_RECORD_ID: 'fldKSFnS37UeQmzNQ',
  TASK_TEMPLATES_LINK: 'fld5FPm767CTRLC1R',
  CALL_COUNT: 'fldEw1v5H3SyekCoZ',
  PATH_CONDITION: 'fldG5Mvt5DzharM3i',
  SED_NOTE: 'fldu64rcx9vPIZXKD',
  FOLLOW_UP_OUTCOME: 'fldqb9Fun4cWf4RYv',
  TASK_DOC_LINKS: 'fldz8YzTtdsVwiJ3I',
  HANDOVER_DOC_LINKS: 'fldZeGpG5VlY1Oiip',
  FILLERS_DOC_LINKS: 'fldxgHjnRVSlYlHbM',
} as const

export const PROJECTS = {
  TABLE_ID: 'tblNYJQt2YWSWxzHP',
  PROJECT_NAME: 'fldB2vFh3LHlF30uq',
  PROJECT_ID: 'fldBjQceUJ8bZm4Qc',
  QUOTATION_NUMBER: 'fldRrZXIY4G8B9tkW',
  QUOTATION_REFERENCE: 'fld9kdlnvEExao7wv',
  PROJECT_STAGE: 'fldnINS8WLH5nkNGK',
  CLIENT_NAME: 'fldq8KO7c05etvfo2',
  SALES_OWNER: 'fld2JiufpGFcKCC6U',
  PAYMENT_MODE: 'fldmdHxh00sNkHqsj',
  PROJECT_TOTAL_COST: 'fldGFCLmYsTam1SIJ',
  TOTAL_PAID: 'fld6BdgaLcTcAMIEH',
  REMAINING_BALANCE: 'fldntJTn8N55eazM2',
  PAYMENT_PROGRESS: 'fld4TAQfEBVufRDez',
  LAST_MODIFIED_TASKS: 'fldl1WQ27xdZREjtv',
  APPROVAL_STATUS: 'fldH2FdeW2yZyNHdz',
  TASKS: 'fldCezGrdho4OveCs',
  PROJECT_ITEMS: 'fldYcgC7XmHzZk9A1',
  PAYMENTS: 'fldtHlJddB54ZHeNZ',
  GATE_PASSES: 'fld7iklMx1CKLXZiw',
  PROJECT_CREATED_AT: 'fldj9TQDO0WZEZBCR',
  MANAGER_NOTES: 'fldr3TvHVibp8QBtg',
  SED_NOTES: 'fldxFwBQKWytFdrBp',
  COMMUN_SEDS: 'fldEs8LgBmhAC4XyQ',
  CLIENT_PHONE: 'flduN1gfUdUaTN3Af',
  CLIENT: 'fldwLVEUsKeVLvXSb',
  ASSIGNED_INSTALLATION_TEAM: 'fldXdHwEqZLdgBgy4',
  NICKNAME: 'fldChERvQwVlxO1nR',
  EMIRATE: 'fldIrxYRfumFm6JjU',
  LOCATION: 'fld5iIjUh9z7jaJFW',
  DETAILED_LOCATION: 'fldoRWDUaeNKEtrbi',
  PROJECT_DESCRIPTION: 'fldhpCCy7ZIrh7pax',
  REQUIRED_INTAKE_PATHS: 'fld5jHSFxBU9euELy',
} as const

export const PROJECT_ITEMS = {
  TABLE_ID: 'tblWg3ijuhV1JsijY',
  ITEM_NAME: 'fldAl0NLXKd89KHXp',
  ITEM_ID: 'fldb21WK8jBSt8fFq',
  PROJECT: 'fldATmKZ7yOVY2MYZ',
  STATUS: 'fldsgg5maMG5Phhvx',
  ITEM_SEQUENCE: 'fldoMCVk5m2mOmfTb',
  TASKS: 'fldDXnVjg1yq7Ed90',
  SED_OWNER: 'fldrM4XWKMwkWaDgD',
  ITEM_CREATED_AT: 'fldPVnEc8tCvwEZIB',
  ITEM_TYPE: 'fldYEzJXbvQEU9i4Z',
  QUANTITY: 'fldkzvi3cCcKzwjFc',
  QUOTATIONS_LINK: 'fldxjXZbDvK39rqJU',
} as const

export const QUOTATIONS = {
  TABLE_ID: 'tbllITZymuWCZ9tde',
  NAME: 'fldgHsELpxTIo2vnC',
  NOTES: 'fldTAsLNGg6OBSXYw',
  PROJECT: 'fldOQ2Ly0sPsqBcje',
  PROJECT_ITEM: 'fld1PRUM7wpcrJXVS',
  DESCRIPTION: 'fldjyDMxYA33ML3K0',
  QUANTITY: 'fldZj6k5Gc23tpVaI',
  UNIT_PRICE: 'fldz9RIVU1xQZgUwT',
  QUOTATION_STATUS: 'fldJjktB8XgZkoYzr',
  SENT_DATE: 'fldxIMge4UKFxJeHV',
  APPROVED_DATE: 'fldURdaSenYkzkWpn',
} as const

export const PAYMENTS = {
  TABLE_ID: 'tblTrLUuGRGt5iSwD',
  NAME: 'fldMKBSDwUUYEwzFu',
  NOTES: 'fldUyVVQukyAjcRGX',
  ASSIGNEE: 'fldx9Ex2woF6NnIzp',
  PROJECT: 'fldzczMvwNb1In9qn',
  AMOUNT: 'fldqduawq8VeBZUY0',
  PAYMENT_TYPE: 'fldoOSKdkyP08LB85',
  PAYMENT_STATUS: 'fld2HEapbHyD8VQ8i',
  PAYMENT_METHOD: 'fldn6iPqvugM5ASC0',
  REFERENCE_NO: 'fldIxzp2gn8ZAnfAD',
  RECEIVED_DATE: 'fld3CNFfxgku2uKvr',
  DUE_DATE: 'fldsD73VfEFT4jwVF',
  ACCOUNTANT_APPROVED: 'fldbpfxYepO2cWMCl',
  STAGE_AT_PAYMENT: 'fldWi6SfcwXI1c1Jb',
  PAYER_TYPE: 'fldPYIgJR10wHyRdK',
  PAYER_NAME: 'fld7lK5GIkQibmLwe',
  COMMISSION_AMOUNT: 'fldqLG1zZiGwBu5XQ',
} as const

export const GATE_PASSES = {
  TABLE_ID: 'tblLu66NWdfPva9Mp',
  NAME: 'fld2s422gcSf2ch4e',
  PROJECT: 'fldLNjM9Z0ujfSmxc',
  ITEMS_DESCRIPTION: 'fldiFsHMgMfCo7xUl',
  ESTIMATED_SUPPLY_DATE: 'fldApKYRSn6boaOTR',
  CONFIRMED_DELIVERY_DATE: 'fldbNn9XqApu67fXu',
  GATE_PASS_STATUS: 'flddMUpnVZevM5y8X',
  SITE_READY: 'fldMfo0s6OPcWXLpp',
  CLIENT_NOTIFIED: 'fld1GxEYGezNjNgcp',
} as const

export const TEAM_MEMBERS = {
  TABLE_ID: 'tbleyX0MkYf1OucMS',
  NAME: 'fldpVNN148goSwWNX',
  SYSTEM_ROLE: 'fldv7Nx8RtYK7IJeq',
  ACTIVE: 'fldtcuYm3JoaSAaRc',
  AIRTABLE_EMAIL: 'fldblbST8aaAd93ZQ',
} as const

export const MAINTENANCE = {
  TABLE_ID: 'tblX5VNBzyFDsuZXD',
  MAINTENANCE_ID: 'fldftAjExMsYzlemR',
  PROJECTS: 'fldQ4TQCNnELwxnPq',
  STATUS: 'fldIWK6um8WZ89Iex',
  START_DATE: 'fld1PsSeVD3a4XXwV',
  END_DATE: 'flduesbwUe6rdBUmV',
  WARRANTY_TYPE: 'fldKz3G4FJA9pxtWK',
} as const

export const ANNOUNCEMENTS = {
  TABLE_ID: 'tbluhehjxkkNcmTMl',
  TITLE: 'fldoL6vSvUjNKQorq',
  MESSAGE: 'fld8nkfkkLi3LEwEo',
  PINNED: 'fldpVhI5NsTQ2tavI',
  VISIBLE_TO: 'fldcOYHIdWkLgo9qk',
  EXPIRES_AT: 'fldSXuvTu3QnJuCEy',
} as const

export const SYSTEM_LOGS = {
  TABLE_ID: 'tblfiHmuJYwiOXRVX',
  EVENT: 'fldQ8tiEOTnknhYPt',
  LEVEL: 'fldfvQUFbTbXPKZzX',
  REQUEST_ID: 'fldn0FfxJy289AhMg',
  USER_ID: 'fldRhs59mgD1jjXeY',
  DURATION_MS: 'fldPBlzfGq5wVRZPn',
  METADATA: 'fldlFHdf8PGgeHLqG',
  TIMESTAMP: 'fld5iJRY4gbiuiez6',
} as const

export const FAILED_REQUESTS = {
  TABLE_ID: 'tblFXMso3NbWMCp29',
  REQUEST_ID: 'fldAmldUiSX295vrW',
  ENDPOINT: 'fldcuuhmJUqRvIVrh',
  METHOD: 'fldZc5KrLBh1187m0',
  EVENT: 'fld31iusnGLuXsSTD',
  ERROR_MESSAGE: 'fldkbUYqSEuY0FlR7',
  STATUS_CODE: 'fldVZVaiMPGIpEEjV',
  INPUT_PAYLOAD: 'fldnUst7Aa9cM49NW',
  REPLAYED: 'fldkVNtk2a9Y2PBDI',
  REPLAY_RESULT: 'fldGxHBVfVCD46HgJ',
  TIMESTAMP: 'fldoLKN6KfeGfbhXN',
} as const


export const PURCHASE_ORDERS = {
  TABLE_ID: 'tblXyum6bJJltk2vE',
  NAME: 'fldULSfblBR9sjGIY',
  PROJECT: 'fldU2ouPvvfzAfiMB',
  SUPPLIER: 'fldCEdbaCZrnMTGCC',
  TOTAL_AMOUNT: 'fldIsLK1Z3a1mcxTB',
  PO_STATUS: 'fldKbowPmATj4SdTl',
  ORDER_DATE: 'fldyMrgYYkcbKmOtt',
  EXPECTED_DELIVERY: 'fldQLOCcLCBJDX2EL',
  ACTUAL_DELIVERY: 'fld9kXKTi8ysfa0Ta',
  MANAGER_APPROVED: 'fld2M9FkIXzuXa8Pa',
  NOTES: 'fldHpUK9omtuhCtIs',
} as const

export const INSTALLATION_LOGS = {
  TABLE_ID: 'tbljrel5tmlHMmJxt',
  NAME: 'fldRGWvQykJcVFCbk',
  PROJECT: 'fldrLAT0he9UmGfjQ',
  DATE: 'fldp4EbfOqn6ez6x0',
  INSTALLATION_TEAM: 'fldWMb8bIisxlARm4',
  NUMBER_OF_LABORERS: 'fldqcpTULWzwcGhq9',
  WORK_DESCRIPTION: 'fldfGXe6BFzxg5akb',
  EXPECTED_FINISH_DATE: 'fldlQLfHsSb74wz6g',
  PHOTOS: 'fld7NCGfaED0ICHXw',
} as const

export const HANDOVER_SHEETS = {
  TABLE_ID: 'tblm5eS4DqQvxELPw',
  HANDOVER_ID: 'fldCyPnEeeoujVNEF',
  PROJECT: 'fldTaOFi4mH8kz1g1',
  STATUS: 'fldXERlcFEgan6q6x',
  NOTES: 'fld3j6U1nWqK3Cy4A',
  PDF: 'fldKBmNaNpvRcWBmt',
  INSTALLATION_LOGS: 'fldYGozo80I5Wyof0',
  MAINTENANCE: 'fldQRDYG8E2YqWWSu',
  FINAL_INSTALLATION_DATE: 'fld26o3FkYIJrEuqW',
  CUSTOMER_SATISFACTION: 'fldghZv3yUbsAdjDI',
  INSTALLATION_DIFFICULTY: 'fldEmFFjXia931YOe',
  NEWSLETTER_OPT_IN: 'fld38IGwc92IrrYAt',
} as const

export const CALENDAR_EVENTS = {
  TABLE_ID: 'tblnG8M3db73zeiNS',
  TITLE: 'fldp3dfc2382m6c1C',
  DATE: 'fld8saVnwII9nstoP',
  NOTES: 'fldRWcbihUAdmyBIg',
  PROJECT: 'fldvK1majrFSNWVxy',
  CREATED_BY: 'flduWnzsPZeIAmprs',
} as const

export const MATERIALS_NEEDED = {
  TABLE_ID: 'tblDTNeiICTwzdi6N',
  NAME: 'fld90lAndpbxEdRM7',
  PROJECTS: 'fld376EMuWX3MFSNJ',
  SUPPLIER: 'fldzXilF4AR3po08n',
  QUANTITY: 'fldPRou9XW1VXpuqC',
  UNIT: 'fldRXpe4lMMAqnGPa',
  UNIT_COST: 'fldrTBQvgsY0srmN0',
  ORDER_STATUS: 'fldV4JDGucrWPvdS0',
  EXPECTED_ARRIVAL_DATE: 'fld939YZMSPblUP1E',
  ACTUAL_ARRIVAL_DATE: 'fldrMTJ0AcUSXrflW',
  PROJECT_ITEMS: 'fld6PhoGUXiwKEoFQ',
  NOTES: 'fldWnu7dJIcKk8GUd',
  PURPOSE: 'fld27k5HcXCdfE39G',
  REQUESTED_BY: 'fld2ghZwrYAe8xk9k',
  REQUEST_DATE: 'fldjzLbseV1m8EDeo',
} as const
