// Generates lib/fieldMap.preview.generated.ts for a SECOND Airtable base (e.g. the
// Preview base) whose table/field IDs differ from the current base. It matches every
// logical `TABLE.FIELD` in lib/fieldMap.ts to the new base BY NAME, using the Airtable
// Meta API, and emits the same nested shape with the new IDs.
//
// Prereqs: the token in AIRTABLE_API_KEY needs `schema.bases:read` on BOTH bases.
// Run: npx tsx scripts/sync-fieldmap.ts <newBaseId>
//   (current base is read from AIRTABLE_BASE_ID in .env.local)
import { config as loadEnv } from 'dotenv'
import { writeFileSync } from 'fs'
import * as FM from '../lib/fieldMap'

loadEnv({ path: '.env.local', override: true })

const API_KEY = process.env.AIRTABLE_API_KEY
const CURRENT_BASE = process.env.AIRTABLE_BASE_ID
const NEW_BASE = process.argv[2]

if (!API_KEY || !CURRENT_BASE) { console.error('Missing AIRTABLE_API_KEY / AIRTABLE_BASE_ID'); process.exit(1) }
if (!NEW_BASE || !/^app[A-Za-z0-9]{14}$/.test(NEW_BASE)) {
  console.error('Usage: npx tsx scripts/sync-fieldmap.ts <newBaseId>')
  process.exit(1)
}

interface MetaField { id: string; name: string }
interface MetaTable { id: string; name: string; fields: MetaField[] }

async function fetchMeta(baseId: string): Promise<MetaTable[]> {
  const res = await fetch(`https://api.airtable.com/v0/meta/bases/${baseId}/tables`, {
    headers: { Authorization: `Bearer ${API_KEY}` },
  })
  if (!res.ok) throw new Error(`meta ${baseId} failed: ${res.status} ${await res.text()} — token needs schema.bases:read`)
  return ((await res.json()) as { tables: MetaTable[] }).tables
}

async function run() {
  const [curTables, newTables] = await Promise.all([fetchMeta(CURRENT_BASE!), fetchMeta(NEW_BASE)])

  // current: tableId → { name, fieldId → fieldName }
  const curById = new Map<string, { name: string; fields: Map<string, string> }>()
  for (const t of curTables) {
    curById.set(t.id, { name: t.name, fields: new Map(t.fields.map((f) => [f.id, f.name])) })
  }
  // new: tableName → { id, fieldName → fieldId }
  const newByName = new Map<string, { id: string; fields: Map<string, string> }>()
  for (const t of newTables) {
    newByName.set(t.name, { id: t.id, fields: new Map(t.fields.map((f) => [f.name, f.id])) })
  }

  const unmatched: string[] = []
  const out: Record<string, Record<string, string>> = {}

  for (const [constName, constObj] of Object.entries(FM)) {
    if (!constObj || typeof constObj !== 'object') continue
    const obj = constObj as Record<string, string>
    const tableIdVal = obj.TABLE_ID ?? obj.TABLE
    if (typeof tableIdVal !== 'string' || !tableIdVal.startsWith('tbl')) continue // not a table const

    const curTable = curById.get(tableIdVal)
    if (!curTable) { unmatched.push(`${constName}: table ${tableIdVal} not in current base`); continue }
    const newTable = newByName.get(curTable.name)
    if (!newTable) { unmatched.push(`${constName}: table "${curTable.name}" not in new base`); continue }

    const mapped: Record<string, string> = {}
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value !== 'string') continue
      if (key === 'TABLE_ID' || key === 'TABLE') { mapped[key] = newTable.id; continue }
      if (!value.startsWith('fld')) { mapped[key] = value; continue } // pass-through non-field values
      const fieldName = curTable.fields.get(value)
      const newId = fieldName ? newTable.fields.get(fieldName) : undefined
      if (!newId) {
        // Keep the original id so the exported shape stays complete; flag for review.
        mapped[key] = value
        unmatched.push(`${constName}.${key} ("${fieldName ?? value}")`)
        continue
      }
      mapped[key] = newId
    }
    out[constName] = mapped
  }

  const body =
    '// AUTO-GENERATED by scripts/sync-fieldmap.ts — do not edit by hand.\n' +
    `// Field/table IDs for the Preview base (${NEW_BASE}).\n\n` +
    `export const PREVIEW = ${JSON.stringify(out, null, 2)} as const\n`
  writeFileSync('lib/fieldMap.preview.generated.ts', body)

  console.log(`\n✓ Wrote lib/fieldMap.preview.generated.ts (${Object.keys(out).length} tables)`)
  if (unmatched.length) {
    console.log(`\n⚠  ${unmatched.length} unmatched field(s) — fix names in the new base and re-run:`)
    for (const u of unmatched) console.log(`   - ${u}`)
    process.exit(2)
  }
  console.log('All fields matched.\n')
  process.exit(0)
}

run().catch((e) => { console.error(e); process.exit(1) })
